#!/usr/bin/env bash
# world wide web
dns_config() {
    subdomain=$1
    domain=$2
    script=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }')
    echo "$script"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]
then
  # display information for default subdomains
  dns_config www "$domain"
  dns_config lb-01 "$domain"
  dns_config web-01 "$domain"
  dns_config web-02 "$domain"
else
  # display information for specified subdomain
  dns_config "$subdomain" "$domain"
fi

