#!/bin/bash

# Install HAproxy
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  my-frontend
        bind *:80
        mode http
        default_backend my-backend
backend my-backend
        balance roundrobin
	server web-01 3.90.85.138:80 check
    	server web-02 18.209.225.8:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
