#!/usr/bin/env bash
# fix container
service nginx stop
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx /var/log/nginx
chmod -R 644 /var/lib/nginx /var/log/nginx
service nginx start
