#!/usr/bin/env bash
# Stop the nginx service if it's already running
service nginx stop
# Update the nginx.conf file to run nginx as the nginx user
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx /var/log/nginx
service nginx start
